---
contentdir: "content"
layoutdir: "layouts"
publishdir: "dist"
theme: "buoy"
indexes:
  category: "categories"
baseurl: "http://bryanl.github.io/doit/"
title: "doit - DigitalOcean Interactive Tool"
canonifyurls: true
...
